name: CI_tests

on: push

jobs:
  testcase-results:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with unittest
      run: pytest flow/flow_processing_input_test.py
    - name: Additional Tests
      run: |
        while read directory; do 
          pytest directory
        done <testdirectories.txt
