name: CI_tests

on: push

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Results
      run: |
        while read directory; do 
          pytest $directory
        done <testdirectories.txt
