name: CI_tests

on: push

jobs:
  TestCases:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: RESULTS
      run: |
        while read directory; do 
          pytest $directory
        done <testdirectories.txt
  Flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade flake8
    - name: Get Changed Files
      id: get_file_changes
      uses: dorner/file-changes-action@v1.2.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        plaintext: true
    - name: RESULTS
      run: |
        for directory in ${{ steps.get_file_changes.outputs.files }}
        do
          if [ ${directory: -3} == ".py" ]; then flake8 $directory; fi
        done
  Pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade pylint
    - name: Get Changed Files
      id: get_file_changes
      uses: dorner/file-changes-action@v1.2.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        plaintext: true
    - name: RESULTS
      run: |
        for directory in ${{ steps.get_file_changes.outputs.files }}
        do
          if [ ${directory: -3} == ".py" ]; then pylint $directory; fi
        done

